# Generated by Django 4.1.4 on 2022-12-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavuch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zavuch',
            options={'verbose_name': 'Завуч', 'verbose_name_plural': 'Завучи'},
        ),
    ]
