# Generated by Django 4.1.4 on 2022-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('sur_name', models.CharField(max_length=10, verbose_name='Фамилия')),
                ('geo', models.CharField(max_length=255, verbose_name='Место проживание')),
                ('phone', models.CharField(help_text='Номер должен содержать только цифры', max_length=12, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директоры',
            },
        ),
    ]
