# Generated by Django 4.1.4 on 2022-12-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sur_name',
            field=models.CharField(max_length=15, verbose_name='Фамилия'),
        ),
    ]
